hdparm: drop NO_GENERIC_LICENSE[hdparm]
* the hdparm license text was added in:
  https://git.openembedded.org/openembedded-core/commit/?id=e9c1f48af10ccb58251ecc7e041babb99b94d6df

  and now the NO_GENERIC_LICENSE was causing:
  ERROR: hdparm-9.65-r0 do_populate_lic: QA Issue: hdparm: hdparm is a generic license, please don't use NO_GENERIC_LICENSE for it. [license-no-generic]

(From OE-Core rev: 64759473f3e6f3a9f3424575591b83ce9cd14e6c)

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>