perl: Undefine d_libm_lib_version.
A recent commit in GLIBC [1] got rid of _LIB_VERSION, which
makes Perl's build fail:
| pp.c:47:5: error: unknown type name '_LIB_VERSION_TYPE'; did you mean '__VERSION__'?
|      _LIB_VERSION_TYPE _LIB_VERSION = _IEEE_;
|      ^~~~~~~~~~~~~~~~~
|      __VERSION__
| pp.c:47:38: error: '_IEEE_' undeclared here (not in a function); did you mean '_SIZET_'?
|      _LIB_VERSION_TYPE _LIB_VERSION = _IEEE_;
|                                       ^~~~~~
|                                       _SIZET_
| make[1]: *** [pp.o] Error 1

The current config.sh enables d_libm_lib_version for
everyone, with special cases left to undefine it as fixup
(such as MUSL [2]).

Since this may only affect some BSDs and Cygwin [3], it
follows that the opposite (defining it) should be a fixup
for those special cases.

[1] https://sourceware.org/git/?p=glibc.git;a=commit;h=813378e9fe17e029caf627cab76fe23eb46815fa
[2] http://cgit.openembedded.org/openembedded-core/tree/meta/recipes-devtools/perl/perl_5.24.1.bb?id=8ca61a5464743ff85b6d26886112750d6ddd13e0#n127
[3] https://perl5.git.perl.org/perl.git/blob/443bd156a6baaf7a8fe6b6b05fcf6c4178140ed2:/pp.c#l42

(From OE-Core rev: f01af4159fe8f75cb1d6a5cbce9cb73e1c8cc19f)

Signed-off-by: Daniel Díaz <daniel.diaz@linaro.org>
Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>