mesa.inc: package 00-radv-defaults.conf
this fixes:

ERROR: mesa-2_22.0.2-r0 do_package: QA Issue: mesa: Files/directories were installed but not shipped in any package:
  /usr/share/drirc.d/00-radv-defaults.conf
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
mesa: 1 installed and not shipped files. [installed-vs-shipped]

(From OE-Core rev: 8d5f5823b357e5bba107511f62cfd0777da2e401)

Signed-off-by: Markus Volk <f_l_k@t-online.de>
Signed-off-by: Luca Ceresoli <luca.ceresoli@bootlin.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
(cherry picked from commit e306dd7d300727852a2794cd78f3097d5999eb58)
Signed-off-by: Steve Sakoman <steve@sakoman.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>