openssl: fix multilib file install conflicts
To avoid issue like below if run "bitbake lib32-core-image-minimal"
with series userspace packages(LAMP,krb5...) added.

Add multilib_script support for openssl's c_rehash which is a perl script.

Error: Transaction check error:
  file /usr/bin/c_rehash conflicts between attempted installs of
  lib32-openssl-bin-1.1.1-r0.armv7at2hf_neon and openssl-bin-1.1.1-r0.aarch64

(From OE-Core rev: a4032f3cc5de451f0e97eca1f0cbe4a310e1560b)

(From OE-Core rev: eb875a7ecb74a9a63d81c64ec770ec65ed5d0211)

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
Signed-off-by: Armin Kuster <akuster808@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>