mesa: fix SRC_URI
ERROR: mesa-2_12.0.1-r0 do_checkuri: Fetcher failure for URL: 'ftp://ftp.freedesktop.org/pub/mesa/12.0.1/mesa-12.0.1.tar.xz'. URL ftp://ftp.freedesktop.org/pub/mesa/12.0.1/mesa-12.0.1.tar.xz doesn't work

change to https and use older-versions path

(From OE-Core rev: dfab5f822c7fd73736953a3883bc16829cd5582e)

Signed-off-by: Armin Kuster <akuster808@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>