bootchart2: Add missing python3-math dependency
Without this dependency, generating the bootchart may fail with:
"
ModuleNotFoundError: No module named 'random'
"

(From OE-Core rev: 487e9f16a00f895159b79f1865fe8b626b47ddc2)

Signed-off-by: Marek Vasut <marex@denx.de>
Cc: Mingli Yu <mingli.yu@windriver.com>
Cc: Richard Purdie <richard.purdie@linuxfoundation.org>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>