kea: fix installation umask to 0022 of meson.
The default installation umask is 0027 for Kea-built artifacts.

And it caused package conflicts as following:
Error: Transaction test error:
  file /usr/lib/pkgconfig conflicts between attempted installs of kea-dev-3.0.1-r0.x86_64_v3 and btrfs-tools-dev-6.16-r0.x86_64_v3
  file /usr/lib/pkgconfig conflicts between attempted installs of libgcrypt-dev-1.11.2-r0.x86_64_v3 and kea-dev-3.0.1-r0.x86_64_v3

I submitted an issue to the upstream and found upstream alreadly known this issue.
https://gitlab.isc.org/isc-projects/kea/-/issues/4171
https://gitlab.isc.org/isc-projects/kea/-/issues/3993

Then I follow the method in the SPEC file of upstream to fix this problem in Yocto.
https://gitlab.isc.org/isc-projects/kea-packaging/-/blob/master/rpm/kea.spec?ref_type=heads
meson setup build \
	--buildtype release \
	--install-umask 0022 \
	--bindir %{_bindir} \

(From OE-Core rev: 0294c265a1f662e2b68b3a462da113cfa835485b)

Signed-off-by: Liu Yiding <liuyd.fnst@fujitsu.com>
Signed-off-by: Mathieu Dubois-Briand <mathieu.dubois-briand@bootlin.com>
Signed-off-by: Ross Burton <ross.burton@arm.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>