testsdk: Avoid PATH contamination
The autobuilder has been seeing increasing numbers of testsdk failures
where xz was 'missing':

ERROR: core-image-sato-1.0-r0 do_testsdk: Couldn't install the SDK:
Error: xz is required for installation of this SDK, please install it first

This is probably due to xz and it's libraries not being in the sysroots
in a way which works without races.

Since the SDK should be using the host, fix this. The eSDK already does
this to solve a similar problem so copy the code from there.

(From OE-Core rev: 39ac3439dfdf2afa67abed4bd32aeb3c14979ded)

Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>