util-linux: fix register location for rfkill to avoid conflict
If we have 'wifi' in distro feature, then busybox would have rfkill
enabled. And we would have the following do_rootfs failure if we
install both busybox and util-linux-rfkill.

  Error: cannot register alternative rfkill to /usr/bin/rfkill since
  it is already registered to /usr/sbin/rfkill.

There's another provider of rfkill in OE, that is rfkill recipe in meta-oe.
And it also registers rfkill to ${sbindir}/rfkill.

So change the register location of rfkill in util-linux to avoid
conflict with busybox and rfkill recipes.

(From OE-Core rev: e01107c5da395a32f9a017f8ee8cc8421c5671e0)

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>