bind: fix build with python3 PACKAGECONFIG enabled
If the PACKAGECONFIG item, python3, is enabled, we get the following
QA issue when multilib is enabled.

  ERROR: bind-9.11.5-P4-r0 do_package: QA Issue: bind: Files/directories were installed but not shipped in any package:
  /usr/lib
  /usr/lib/python3.7
  /usr/lib/python3.7/site-packages
  /usr/lib/python3.7/site-packages/isc-2.0-py3.7.egg-info
  /usr/lib/python3.7/site-packages/isc
  /usr/lib/python3.7/site-packages/isc/policy.py
  [snip]

The thing is, when --with-python is specified with a path instead of 'yes',
the --with-python-install-dir is in fact ignored.

Fix this issue by specifying the correct arguments.

(From OE-Core rev: 2c36b3e5c7caae07ffe0cfb816d37fad52d69fc9)

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>