mc: set ac_cv_path_ZIP to avoid buildpaths QA issues
* in builds with zip in HOSTTOOLS mc fails with:
  ERROR: mc-4.8.31-r0 do_package_qa: QA Issue: File /usr/libexec/mc/extfs.d/uzip in package mc-helpers-perl contains reference to TMPDIR [buildpaths]
  and it's because of the path to zip:
  mc/4.8.31/package $ grep -R styhead .
  ./usr/libexec/mc/extfs.d/uzip:my $app_zip = "TMPDIR/hosttools/zip";

* don't use /usr/bin/env as in other cases, because app_zip is then used e.g. with:
  my $cmd_addlink = "$app_zip -g -y";

(From OE-Core rev: 24df179cdb8c89c54d1864862afa2692bb7c659f)

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>
Signed-off-by: Alexandre Belloni <alexandre.belloni@bootlin.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>