ruby: upgrade 2.6.5 -> 2.7.0
0003-configure.ac-check-finite-isinf-isnan-as-macros-firs.patch
Removed since it is included in 2.7.0.

refresh the following patch:
0002-Obey-LDFLAGS-for-the-link-of-libruby.patch

add the following patch to solve build error:
0001-Modify-shebang-of-libexec-y2racc-and-libexec-racc2y.patch
[error message]
ERROR: ruby-2.7.0-r0 do_package_qa: QA Issue:
/usr/lib/ruby/gems/2.7.0/gems/racc-1.4.16/bin/y2racc contained in
package ruby requires /usr/local/bin/ruby, but no providers found in
RDEPENDS_ruby? [file-rdeps]

format of file COPYING is updated.
LEGAL notice information is updated.

(From OE-Core rev: 3cdf5da514b424a6d78ba4e1412331b6cf2b3bff)

Signed-off-by: Wang Mingyu <wangmy@cn.fujitsu.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>