manuals: fix quoting of double dashes
Otherwise rendered as "en" dashes by sphinx, for example:
git pull –rebase
instead of
git pull --rebase

Readers could confuse them with normal dashes.

Exception: replace by \-\- in italic text (*text*)
as Sphinx cannot nest italic and quoted text.

For consistency, also update quoting in strings in the same code hunks.

(From yocto-docs rev: 4e7ce372e37f76148f623a5295a15e08bc2603ff)

Signed-off-by: Michael Opdenacker <michael.opdenacker@bootlin.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>