llvm: multilib-header fix for llvm/Config/llvm-config.h
Fix following conflicts when enabling multilib.

Error: Transaction test error:
  file /usr/include/llvm/Config/llvm-config.h conflicts between attempted installs of lib32-llvm-dev-21.1.3-r1.core2_32 and llvm-dev-21.1.3-r1.x86_64_v3

(From OE-Core rev: 886b0fb60a0b2ebbe3186c790db6e0a41eeb8741)

Signed-off-by: Liu Yiding <liuyd.fnst@fujitsu.com>
Signed-off-by: Mathieu Dubois-Briand <mathieu.dubois-briand@bootlin.com>
Signed-off-by: Ross Burton <ross.burton@arm.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>