parselogs.py: ignore rndr initialization failure
After rng-tools upgraded to 6.13, the RNDR instruction added
as an entropy source [1]. But for some cpu which doesn't support
rndr, there comes below warning message:
 # systemctl status rngd
 [snip]
 Jul 20 06:48:07 qemuarm64 rngd[163]: [rndr  ]: No HW SUPPORT
 Jul 20 06:48:07 qemuarm64 rngd[163]: [rndr  ]: Initialization Failed
 [snip]

Actually the failed message doesn't matter as it only indicates
one entropy source rndr fails to initialize and won't affect rngd
function, so ignore the failure message to fix below error during
do_testimage.
NOTE: ======================================================================
NOTE: FAIL: test_parselogs (parselogs.ParseLogsTest)
NOTE: ----------------------------------------------------------------------
NOTE: Traceback (most recent call last):
  File "/build/layers/oe-core/meta/lib/oeqa/core/decorator/__init__.py", line 36, in wrapped_f
    return func(*args, **kwargs)
  File "/build/layers/oe-core/meta/lib/oeqa/runtime/cases/parselogs.py", line 382, in test_parselogs
    self.assertEqual(errcount, 0, msg=self.msg)
AssertionError: 1 != 0 : Log: /build/tmp/work/qemuarm64-wrs-linux/wrlinux-image-std/1.0-r5/target_logs/daemon.log
-----------------------
Central error: 2021-06-23T20:44:18.374494+00:00 qemuarm64 rngd[162]: [rndr  ]: Initialization Failed

(From OE-Core rev: 1edc840d6921668b69d248f9b32fa1d5c95e3138)

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>