neon: fix fetch error
ERROR: neon-native-0.30.1-r0 do_checkuri: Fetcher failure for URL: 'http://www.webdav.org/neon/neon-0.30.1.tar.gz'. URL http://www.webdav.org/neon/neon-0.30.1.tar.gz doesn't work
ERROR: neon-native-0.30.1-r0 do_checkuri: Function failed: do_checkuri

change to https and url to OSL.
www.webdav.org is down or dean

(From OE-Core rev: 5bf1ce30cbafe12b72e8215ed86d115cb22851c4)

Signed-off-by: Armin Kuster <akuster808@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>