xtrans: Fix multilib .pc file conflict
Error: Transaction check error:
  file /usr/share/pkgconfig/xtrans.pc from install of lib32-xtrans-dev-1:1.3.5-r0.core2_32 conflicts with file from package xtrans-dev-1:1.3.5-r0.core2_64

[YOCTO #12511]

(From OE-Core rev: e20da6dec99c4d2e6b803b07f8f79af0c54d1396)

Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>