linux-yocto/4.1: fix musb compilation error
We had a partial musb change merged into the 4.1 tree, which resulted in:

  | kernel-source/drivers/usb/musb/musb_dsps.c:
  In function 'dsps_create_musb_pdev':
  | kernel-source/drivers/usb/musb/musb_dsps.c:750:8:
  error: 'struct musb_hdrc_config' has no member named 'maximum_speed'
  |   config->maximum_speed = usb_get_maximum_speed(&parent->dev);
  |         ^~

By backporting commit:

  9b7537642cb6a [usb: musb: set the controller speed based on the config setting]

We get our missing structure field, and we can once again build musb.

[YOCTO: #9680]

(From OE-Core rev: b746223787a0195c3a4d16523003c62ec0ac8451)

(From OE-Core rev: b6b0a40e5c9ffe1a2150b36cb2a447a1361d474b)

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
Signed-off-by: Armin Kuster <akuster@mvista.com>

fixup as meta hash was not updated to latest
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>