mtd-utils: fix flash_eraseall installation conflict
override correctly busybox's applet when CONFIG_FLASH_ERASEALL=y is set

Error: update-alternatives: not linking /builds/image/1.0-r0/rootfs/usr/
sbin/flash_eraseall to /bin/busybox.nosuid since /builds/image/1.0-r0/
rootfs/usr/sbin/flash_eraseall exists and is not a link

(From OE-Core rev: 21d5a52d86a4090f7ddb1a9eb41bb143261f890e)

Signed-off-by: Andrej Valek <andrej.valek@siemens.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>