linux-yocto/3.2/3.4: arm: Fix linking errors with binutils 2.23
Updating the 3.2/3.4 linux-yocto SRCREVs to pickup the following fix:

    arm: Fix linking errors with binutils 2.23

    We end up with linking errors on arm using latest binutils
    because we are linking asm generated objects which use -march=all
    generating different attributes into object and use some c objects
    e.g. misc.o which use different march therefore generating a
    different set of attributes into object. When linking is done
    the ld complains since it finds incompatible attributes and ends
    up with errors like

    error: DIV usage mismatch between arch/arm/boot/compressed/head.o and
    output
    error: DIV usage mismatch between arch/arm/boot/compressed/misc.o and
    output
    error: DIV usage mismatch between arch/arm/boot/compressed/decompress.o
    and output
    error: DIV usage mismatch between arch/arm/boot/compressed/lib1funcs.o
    and output

    This patch fixes it by providing correct march to assembly routines
    which than matches with output of ld.

    Signed-off-by: Khem Raj <raj.khem@gmail.com>

(From OE-Core rev: e67ffb708522a622d149641ea09b249259ed3fb4)

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>