vulkan-samples: convert debugfix.patch to git format patch
devtool modify on vulkan-samples fails to apply the debugfix.patch
because it is not in one of git's known formats.

Here is the error:
ERROR: Applying patch 'debugfix.patch' on target directory '<..>/build/tmp/work/core2-64-poky-linux/vulkan-samples/git/devtooltmp-38uz7jyq/workdir/git'
CmdError("sh -c 'git add -f -A .'", 0, 'stdout:
stderr: fatal: not a git repository (or any of the parent directories):
.git
')

Also, rename debugfix.patch to something more meaningfull

(From OE-Core rev: c05c508cf3141a6923d87e1d04f7387ce3c91a9d)

Signed-off-by: Julien Stephan <jstephan@baylibre.com>
Signed-off-by: Luca Ceresoli <luca.ceresoli@bootlin.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>