vulkan-samples: fix do_compile failure
fix error:
| framework/lib/ppc/libframework.a(device.cpp.o): in function `std::__atomic_base<unsigned long long>::load(std::memory_order) const':
| /usr/include/c++/10.2.0/bits/atomic_base.h:426: undefined reference to `__atomic_load_8'

some arch don't have built-in atomic, so need to link it
explicitly

(From OE-Core rev: 65410c5ff4f9c34758d1e2270132c631166e7d1a)

Signed-off-by: Changqing Li <changqing.li@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>