gdb: upgrade 13.1 -> 13.2
Fixes:

 * PR testsuite/30158 (rustc testsuite fails with 13.1, apparently worked before with trunk 20230114 on i686-linux-gnu and powerpc64le-linux-gnu)

 * PR gdb/30214 (GDB 13.1 does not compile on FreeBSD 13.1)

 * PR gdb/30240 ((linux/aarch) thread.c:86: internal-error: inferior_thread: Assertion `current_thread_ != nullptr' failed)

 * PR gdb/30249 ([13 regression] hookpost-extended-remote will not work)

 * PR exp/30271 (Addresses of static thread_local fields are badly calculated sometimes)

 * PR symtab/30357 (Segmentation fault for the 'start' command)

 * PR symtab/30369 ([gdb/symtab] False match issue in skip_prologue_using_linetable)

 * PR gdb/30423 (Build failures with clang 16)

 * PR build/30450 (Build failure (linux-low.cc:5393:45: error: expected ':' before ')' token) with musl-1.2.4)

(From OE-Core rev: 900379776878c363ff7c802f6b740ee89661ea9c)

Signed-off-by: Alexander Kanavin <alex@linutronix.de>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
(cherry picked from commit d10764916624f61d39cb9ea368359837156ad960)
Signed-off-by: Steve Sakoman <steve@sakoman.com>