qemu-system-native: disable options not included in extended tarball
* Add PACKAGECONFIG option for xkbcommon
qemu-keymap.c:16:10: fatal error: xkbcommon/xkbcommon.h: No such file or directory

* Add PACKAGECONFIG option and patch for libudev
commands-posix.c:53:10: fatal error: libudev.h: No such file or directory

* Add PACKAGECONFIG option for libxml2
util/osdep.c:136: undefined reference to `fcntl64'

- Without specifying libxml2, configure searches the system and pulls in the system
  libxml2 if it is present. In the process it adds -L/usr/lib64 which causes the
  system libc to be linked instead of the one from the extended tarball.

None of the above libraries appear to be included in the depends for any of the qemu
builds, so if they are getting linked in, its probably not intentionally.

(From OE-Core rev: 3f1fd15cf0df4a4b12d49ac795b1c9e02de61429)

Signed-off-by: Jeremy Puhlman <jpuhlman@mvista.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>