file: add few more PACKAGECONFIGs to avoid autodetected deps from host
* there are few more autodetected compression libs
  --disable-zlib          disable zlib compression support [default=auto]
  --disable-bzlib         disable bz2lib compression support [default=auto]
  --disable-xzlib         disable liblzma/xz compression support
  --disable-zstdlib       disable zstdlib compression support [default=auto]
  --disable-lzlib         disable liblz (lzip) compression support

  and lzlib was detected on my gentoo (even when it doesn't say that default
  is auto detection)

  I've noticed this, because I've reused sstate-cache from my gentoo build
  in docker container with ubuntu-23.04 and esdk.oeSDKExtSelfTest.test_install_libraries_headers
  test was now failing with:

  Exception: subprocess.CalledProcessError: Command '/OE/build/poky/build/build-st-2023-03-12-esdk-patch1/esdk.oeSDKExtSelfTest.test_install_libraries_headers/build-st/tmp/work/x86_64-nativesdk-pokysdk-linux/buildtools-tarball/1.0-r0/recipe-sysroot-native/usr/bin/createrepo_c --update -q /OE/build/poky/build/build-st-2023-03-12-esdk-patch1/esdk.oeSDKExtSelfTest.test_install_libraries_headers/build-st/tmp/work/x86_64-nativesdk-pokysdk-linux/buildtools-tarball/1.0-r0/oe-sdk-repo' returned non-zero exit status 127.

  Subprocess output:
  /OE/build/poky/build/build-st-2023-03-12-esdk-patch1/esdk.oeSDKExtSelfTest.test_install_libraries_headers/build-st/tmp/work/x86_64-nativesdk-pokysdk-linux/buildtools-tarball/1.0-r0/recipe-sysroot-native/usr/bin/createrepo_c: error while loading shared libraries: liblz.so.1: cannot open shared object file: No such file or directory

  and liblz.so.1 ended in createrepo_c.real because of libmagic.so from file-native-replacement.

* use PACKAGECONFIG for seccomp as well and keep it disabled as it was
  explicitly disabled before (${@bb.utils.filter('DISTRO_FEATURES', 'seccomp', d)}
  can be added to default PACKAGECONFIG later if someone finds it useful)

(From OE-Core rev: b7c51fe740f00f60c591099fe5c2155b2126068c)

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>