nfs-utils: fix do_package error when enable PACKAGECONFIG[nfsv4]
Fixes:
ERROR: nfs-utils-2.4.3-r0 do_package: QA Issue: nfs-utils:
Files/directories were installed but not shipped in any package:
/usr/lib/libnfsidmap/nsswitch.so
/usr/lib/libnfsidmap/static.so
Please set FILES such that these items are packaged. Alternatively if
they are unneeded, avoid installing them or delete them within do_install.
nfs-utils: 2 installed and not shipped files. [installed-vs-shipped]

Add rdep on python3-core for PACKAGECONFIG[nfsv4] to fix:
ERROR: nfs-utils-2.4.3-r0 do_package_qa: QA Issue: /usr/sbin/clddb-tool
contained in package nfs-utils requires /usr/bin/python3, but no
providers found in RDEPENDS_nfs-utils? [file-rdeps]

Add rdep on libdevmapper for PACKAGECONFIG[nfsv41] to fix:
ERROR: nfs-utils-2.4.3-r0 do_package_qa: QA Issue: /usr/sbin/blkmapd
contained in package nfs-utils requires libdevmapper.so.1.02()(64bit),
but no providers found in RDEPENDS_nfs-utils? [file-rdeps]

(From OE-Core rev: 17b44d51eaf71ae6d04034454dcb68f508b85258)

Signed-off-by: Yi Zhao <yi.zhao@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>