dev-manual/bmaptool.rst: correct command for bmaptool-native
Using only "bitbake bmaptool-native", running "oe-run-native bmaptool-native bmaptool ..."
fails as follows:

Error: Have you run 'bitbake bmaptool-native -caddto_recipe_sysroot'?

Running the "bitbake bmaptool-native -caddto_recipe_sysroot" target
is actually sufficient.

(From yocto-docs rev: 8c08d627127866194aea1ca19b1e4055fe5e7b9f)

Signed-off-by: Michael Opdenacker <michael.opdenacker@rootcommit.com>
Reviewed-by: Antonin Godard <antonin.godard@bootlin.com>
Signed-off-by: Antonin Godard <antonin.godard@bootlin.com>
(cherry picked from commit 72fe904a3bbb5e2c7279ab1f119c2beca200dcf2)
Signed-off-by: Antonin Godard <antonin.godard@bootlin.com>
Signed-off-by: Steve Sakoman <steve@sakoman.com>