elfutils: Do not suppress stringop-overflow warning on build hosts
stringop-overflow is a gcc specific option and when we try to use non-gcc
compiler as host compiler e.g. clang, this causes several configure tests to fail
because clang reports this as an option it does not understand and bails out

error: unknown warning option '-Werror=stringop-overflow'; did you mean '-Werror=shift-overflow'? [-Werror,-Wunknown-warning-option]

One of the failing tests is the check for PIC support in compiler and results
in errors during compilation like

/usr/bin/ld: libelf_pic.a(elf_error.os): relocation R_X86_64_TPOFF32 against `global_error' can not be used when making a shared object; recompile with -fPIC

and elfutils-native failing to build with clang as host compiler

This patch was added to support version of fedora in 2022 and the error
has since been addressed in glibc [1]

This is effectively reverting bb76fe2baf00b0874d221445c9fba4481740024f

[1] https://sourceware.org/bugzilla/show_bug.cgi?id=29141

(From OE-Core rev: 2c134301b55892ecf3c0ae9fa4912bc827579ece)

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Mathieu Dubois-Briand <mathieu.dubois-briand@bootlin.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>