glew: Fix build errors at recipes depending on glew
Glew headers override mesa headers by setting mesa's include guards. This
stopped working since mesa renamed them.

Fixes errors like this in depending recipes:

| <...>/recipe-sysroot/usr/include/GL/glext.h:12066:105: error: conflicting declaration 'typedef void (* PFNGLFRAGMENTLIGHTFVSGIXPROC)(GLenum, GLenum, const GLfloat*)'
|  typedef void (APIENTRYP PFNGLFRAGMENTLIGHTFVSGIXPROC) (GLenum light, GLenum pname, const GLfloat *params);
|                                                                                                          ^

(From OE-Core rev: fd6ca8f7453230bac4cd1145406a55549ad43e71)

Signed-off-by: Andreas Müller <schnitzeltony@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>