uninative-tarball: Add libjis and euc-jp gconv files
packages like fontforge-native fail with mysterious errors like

| ../../git/inc/gwwiconv.h:44:21: error: conflicting types for ‘gww_iconv_close’
|  #define iconv_close gww_iconv_close
|                      ^~~~~~~~~~~~~~~
| ../../git/inc/gwwiconv.h:37:13: note: previous declaration of ‘gww_iconv_close’ was here
|  extern void gww_iconv_close( gww_iconv_t cd);
|              ^~~~~~~~~~~~~~~

The reason behind this is that a check for iconv fails during native
configure run, the check fails because the autoconf test to check for iconv
pokes for these gconv's in test runs before declaring iconv support successful.

Therefore when uninative is active the package fails to build but when
uninative is inactive all works fine. this patch fixes that

(From OE-Core rev: b4f5ed7a8bb2f76ab4a50b3f0073a9d18a51923e)

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>