systemd: check IFLA_VLAN_PROTOCOL
The older kernel's linux/if_link.h doesn't have IFLA_VLAN_PROTOCOL, we need
check whether it has been defined or not.

The maintainer said that he would fix it:

http://thread.gmane.org/gmane.comp.sysutils.systemd.devel/18200

Also we need redefine IFLA_MAX from 34 to 35 when define IFLA_CARRIER,
otherwise there would be error:

| src/libsystemd/sd-rtnl/rtnl-types.c:233:9: error: array index in initializer exceeds array bounds
|          [IFLA_CARRIER]          = { .type = NLA_U8 },

[YOCTO #6380]

(From OE-Core rev: 0e626d5023fee4dbcc5d94e6b787b4c5fe4b2687)

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>