bitbake: build: Make exception printing clearer
Shows:

ERROR: SystemExit(1)

instead of:

ERROR: 1

(Bitbake rev: df89e37c33e4398a5f8ece9a8b973be3fe2ff361)

Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>