apt: Fix do_compile error when enable ccache
Fixed:
apt-pkg/libapt-pkg.so.5.0.2: undefined reference to `ZSTD_endStream'
collect2: error: ld returned 1 exit status

This is because ccache-native depends on zstd-native which makes apt wronly
find it. Disable zstd for apt to fix the problem.

(From OE-Core rev: 0aa7d612b8b7e5f14b4ed38f2a32b3f7eefca31c)

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>