bitbake: build: Make exception printing clearer
Shows:

ERROR: SystemExit(1)

instead of:

ERROR: 1

(Bitbake rev: 16bb44e00fcad8daefd3b79c5564d9c8a0d03a6c)

Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
(cherry picked from commit df89e37c33e4398a5f8ece9a8b973be3fe2ff361)
Signed-off-by: Anuj Mittal <anuj.mittal@intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>