glibc: unify wordsize.h between arm and aarch64
Make sure this header file is same in arm and aarch64.

Fix the conflict error when enable multilib:
Error: Transaction test error:
  file /usr/include/bits/wordsize.h conflicts between attempted installs of lib32-libc6-dev-2.35-r0.armv7vet2hf_vfp and libc6-dev-2.35-r0.cortexa57

(From OE-Core rev: 402ba8367f5316fd8d25a536ebd12bc0bcdfa400)

Signed-off-by: Yi Zhao <yi.zhao@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>