kernel-devsrc: remove 64 bit vdso cmd files
In a similar way to the other architectures, 64 bit arches
can also require vdso generation. If we leave the .cmd files
around, they'll be packaged and generate build errors:

   ERROR: kernel-devsrc-1.0-r0 do_package_qa: QA Issue: File /usr/lib/modules/6.10.0-yocto-standard/build/include/generated/.vdso64-offsets.h.cmd in package kernel-devsrc contains reference to TMPDIR [buildpaths]
So we add the file to our remove list and avoid the issue.

(From OE-Core rev: 0a9e8fcd29cf6feae437d202baea52775eca5af9)

Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
(cherry picked from commit 0238a49f57c83600909b0f3773a1569bcd13551c)
Signed-off-by: Steve Sakoman <steve@sakoman.com>