btrfs-tools: only target requires udev
The native doesn't have to depend on udev, fixed:

$ bitbake btrfs-tools-native

ERROR: Nothing PROVIDES 'udev-native' (but virtual:native:btrfs-tools_4.8.5.bb DEPENDS on or otherwise requires it). Close matches:
[snip]

(From OE-Core rev: 48e0174aaf7201cb0ee0b15381638213171fa208)

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>