linux-yocto/4.12: add ssl and utils native dependencies
Via the -stable updates, and other configuration changes the 4.12 kernel has the
same dependency on openssl headers as 4.14+.

So we add the same DEPENDS line that we already have in newer kernels to avoid the
following error:

   |   HOSTCC  scripts/sign-file
   | build/tmp/work-shared/qemux86-64/kernel-source/scripts/sign-file.c:25:30: fatal error: openssl/opensslv.h: No such file or directory
   | compilation terminated.
   | scripts/Makefile.host:107: recipe for target 'scripts/sign-file' failed
   | make[3]: *** [scripts/sign-file] Error 1
   | make[3]: *** Waiting for unfinished jobs....

(From OE-Core rev: 80f6840baecb8b161f6443f3dd1af4e70b5e5221)

(From OE-Core rev: 8660345a665ef74828036c89257bc23246243c40)

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
Signed-off-by: Armin Kuster <akuster808@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>