man-pages: use alternatives to resolve crypt.3 conflict
To fix:

  Error: Transaction check error:
    file /usr/share/man/man3/crypt.3 conflicts between attempted installs
    of libcrypt-doc-4.4.1-r0.core2_64 and man-pages-4.16-r0.core2_64

This issue came about after commit 59be9254df9f [libxcrypt: Upgrade to
4.4.1 release].

(From OE-Core rev: c4e0034cd1f020cfb074c7c80af281683752afeb)

Signed-off-by: Mark Asselstine <mark.asselstine@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>