image_types_wic: Remove incorrect MLPREFIX to already prefixed virtual/
Avoid dependency on unavailable virtual/lib32-arm-distromllib32-linux-gnueabi-binutils

MLPREFIX was dropped from other cases in:
https://git.openembedded.org/openembedded-core/commit/?id=6856fc5c848cc2564bebe03a007ef109f46d0adb

This was causing:
  ERROR: Nothing PROVIDES 'virtual/lib32-arm-distromllib32-linux-gnueabi-binutils' (but virtual:multilib:lib32:oe-core/meta/recipes-core/images/core-image-minimal.bb DEPENDS on or otherwise requires it). Close matches:
    virtual/arm-distromllib32-linux-gnueabi-binutils
    virtual/lib32-arm-distromllib32-linux-gnueabi-compilerlibs
    virtual/lib32-arm-distromllib32-linux-gnueabi-go-runtime
  ERROR: Required build target 'lib32-core-image-minimal' has no buildable providers.
  Missing or unbuildable dependency chain was: ['lib32-core-image-minimal', 'virtual/lib32-arm-distromllib32-linux-gnueabi-binutils']

in cases where multilib and WIC were enabled at the same time

(From OE-Core rev: d7644212a17537e9966218fbb99f21a64569f322)

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>