waffle: The surfaceless-egl and gbm requires opengl
Fixed when opengl is not in DISTRO_FEATURES:
ERROR: Nothing PROVIDES 'virtual/libgbm' (but /path/to/waffle/waffle_1.7.0.bb DEPENDS on or otherwise requires it)

(From OE-Core rev: a762162fa0f51b9c6187fd1fcfaad2f317f8762e)

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>