lttng-ust: Fix for --enable-python-agent
Fixed:
PACKAGECONFIG_append_pn-lttng-ust = ' python3-agent'

require conf/multilib.conf
MULTILIBS = "multilib:lib32"
DEFAULTTUNE_virtclass-multilib-lib32 = "x86"

$ bitbake lttng-ust
ERROR: lttng-ust-2_2.10.4-r0 do_package: QA Issue: lttng-ust: Files/directories were installed but not shipped in any package:
  /usr/lib
  /usr/lib/python3.7
  /usr/lib/python3.7/site-packages
  /usr/lib/python3.7/site-packages/lttngust-2.10.4-py3.7.egg-info

(From OE-Core rev: d1b1bfece08ae32c120844d73aadee96de7bbf9b)

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>