linux-yocto/ppc: add elfutils-native to DEPENDS
powerpc joins x86 and ARM requiring elfutils-native in some
configurations.

We already have this dependency in the dev kernel and in devsrc, so we
add it to linux-yocto.inc to ensure that all reference kernels pick up
the requirement.

Without this, objtools fails to build as follows:

   kernel-source/tools/objtool/include/objtool/elf.h:10:10: fatal error: gelf.h: No such file or directory

(From OE-Core rev: 358bab3da997937f3b0f59d65e19a4aea8a1ef98)

Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>