poky.yaml.in: add missing locales dependency
This is a requirement for building the documentation, otherwise we get
(on Ubuntu 24.04):

     File "/usr/lib/python3.12/locale.py", line 615, in setlocale
       return _setlocale(category, locale)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   locale.Error: unsupported locale setting

(From yocto-docs rev: cecf8bc678756790e9164000769e798be30d9d46)

Signed-off-by: Antonin Godard <antonin.godard@bootlin.com>
(cherry picked from commit 0943a7b67ef0012b5d9badc15e0c579dbb9014ae)
Signed-off-by: Antonin Godard <antonin.godard@bootlin.com>
Signed-off-by: Steve Sakoman <steve@sakoman.com>