build-appliance-image: ensure pod2man present in BA
"pod2man" went missing from BA, but it is required.
This patch fixes the Toaster error:

<...>
ERROR: These tools appear to be unavailable in PATH, please install
   them in order to proceed:
       pod2man
<...>

[YOCTO#11144]

(From OE-Core rev: 562c184d52db2182eafde3cf9866606145784deb)

Signed-off-by: Juro Bystricky <juro.bystricky@intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>