acpica: update to 20240322 release
Update acpica to the latest version, comprised of the following commits:

	170fc3076a86 Update changes.txt for new ACPICA release 20240322
	718374cd1bc2 Update acpixf.h for new ACPICA release 20240322
	d0349632b625 Update osunixxf.c license header from 2023 to 2024
	c929bc0d5028 Update osunixmap.c license header from 2023 to 2024
	78c34e3738bd Update osunixdir.c license header from 2023 to 2024
	193a3dda90e2 Update oslinuxtbl.c license header from 2023 to 2024
	edaf61c8a97d Update oszephyr.c license header from 2023 to 2024
	1c5331ede7ec Update osgendbg.c license header from 2015 to 2024
	ab10380db037 Update osbsdtbl.c license header from 2023 to 2024
	815db2de4317 Update osefixf.c license header from 2023 to 2024
	a4dab90c90a4 Update osefitbl.c license header from 2023 to 2024
	4f9205ae4283 Update oseficlib.c license header from 2023 to 2024
	68bc01cec3b9 Update efihello.c license header from 2023 to 2024
	f71b9942deeb Update acdragonfly.h license header from 2003 to 2024
	74fb08369867 Update acgetline.c license header from 2023 to 2024
	c18edfb1abfb Update the copyright year in the license header from 2023 to 2024
	d58f24933d2f Get rid of MSVC warnings that arise actually due to GCC's new dangling pointer warning and also tGCC's blindspot to work with nested named structs/unions resulting in breaking of ACPI event-handling
	ba8a36b5c734 events/evgpeinit: don't forget to increment registered GPE count
	8affc87afd28 events/evxfgpe: correctly clear GPE_AUTO_ENABLED in AcpiSetupGpeForWake
	69f81815f830 Fix Capabilities[1024] mess
	3e89d40e19fc Update actbl2.h to get rid of the MSVC error C2233
	a0ad1ed5105f Fix CXL 3.0 structure (RDPAS) in the CEDT table
	9061cd9aa131 ACPICA: debugger: check status of AcpiEvaluateObject in AcpiDbWalkForFields
	b9423c1d35b0 SRAT: Add dump and compiler support for RINTC affinity structure
	93caddbf2f62 SRAT: Add RISC-V RINTC affinity structure
	9788e0dc955b Modify ACPI_OBJECT_COMMON_HEADER
	a6a236c44c7d Fix spelling and typos: Clean up the fix for Issue #900
	b6b38edb0c18 Clean up the fix for Issue #900
	8f789f356fb5 tests/common: use CopyObject instead of Store for NRMT
	bce7c55e99a0 acgcc: Fix C++ issue with ACPI_FLEX_ARRAY
	e3afd8e17bc8 MADT: Add new MADT GICC/GICR/ITS non-coherent flags handling
	453a5f675677 MADT: Add GICC online capable bit handling
	6cd47047aca6 Fix various spelling mistakes in text files and code comments
	31a16a32e7f3 acpisrc: Add identifiers for the NHLT table
	32260f5ce519 NHLT: Reintroduce types the table consists of
	6ab5a3bb1608 AdDisassemblerHeader: omit timestamp for deterministic output
	471de8b63a98 Fix build indeterminism for asm compiler header.
	50aec3ad9364 os_specific: zephyr: update AcpiOsGetTimer with arch specific timer
	10ae1038e51e osal: zephyr: Fix write access for mapped memory
	3944ce4dd104 osal: zephyr: Fix AcpiOsPrintf implementation
	a97db76b5f1c Fix issue #896
	f5910dd1ab60 Attempt 1 to fix issue #900
	c581606cf49b ACPI 6.5: RAS2: Add support for RAS2 table
	673fc21311ff Add port definitions for CDAT SSLBIS
	9c5649bd2c65 dmtbdump2: remove redundant failure check on Status
	544938c98a7a dmtbdump: remove duplicated code for both paths of an if statement
	0c7379eae2a0 NHLT: Drop preliminary support
	7b10fafca61f Revert "NHLT: Declare device configuration types"
	0333c2af1317 os_specific: zephyr: add generic platform support
	2872257aab53 Fix segfault when error-checking mixed table types
	c7171588a9f6 actbl1.h: Add EINJ CXL error types
	da740d8d27ff Get rid of // style comments
	75635cb363c6 NHLT: Declare device configuration types
	bbd7aee285ca dmtbinfo2.c: RISC-V: Remove redundant Flags print

License-Update: copyright years

(From OE-Core rev: 6059f8eb8097079142bb35fe46c55f3b6e68d1fc)

Signed-off-by: Jon Mason <jdmason@kudzu.us>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>