python3-hypothesis: revert back to 6.46.11
This package was broken since it was upgraded to 6.48, because
it started using 'exceptiongroup' since then, which is missing
in any meta layer. On target, when importing hypothesis, we meet
the following error:

  Traceback (most recent call last):
  File "/usr/lib64/python3.10/site-packages/hypothesis/internal/compat.py", line 18, in <module>
  BaseExceptionGroup = BaseExceptionGroup
  NameError: name 'BaseExceptionGroup' is not defined. Did you mean: 'BaseException'?
  ModuleNotFoundError: No module named 'exceptiongroup'

The related codes as below:
try:
    BaseExceptionGroup = BaseExceptionGroup
    ExceptionGroup = ExceptionGroup  # pragma: no cover
except NameError:
    from exceptiongroup import (
        BaseExceptionGroup as BaseExceptionGroup,
        ExceptionGroup as ExceptionGroup,
    )

We can see that it tries to use ExceptionGroup and falls back to
use an import from exceptiongroup module.

Looking at the https://github.com/agronholm/exceptiongroup, it says:
"""
This is a backport of the BaseExceptionGroup and ExceptionGroup classes from Python 3.11.
"""

So instead of adding a new recipe for exception group, it might be
better to revert to a working version and wait for python 3.11 to release.

(From OE-Core rev: 37c5b171d7de25b131e77b80d37f8481308bd6fe)

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>
Signed-off-by: Luca Ceresoli <luca.ceresoli@bootlin.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>