texinfo: upgrade to 6.5
Besides revision change, this version includes the project M4 macros path into
EXTRA_AUTORECONF which avoid the following compilation issue:

    In file included from ../../../texinfo-6.5/gnulib/lib/mbrtowc.c:21:0:
    ./wchar.h:571:6: error: #if with no expression
     # if
          ^
    Makefile:1378: recipe for target 'mbrtowc.o' failed
    make[4]: *** [mbrtowc.o] Error 1
    make[4]: *** Waiting for unfinished jobs....
    In file included from ../../../texinfo-6.5/gnulib/lib/mbswidth.c:33:0:
    ./wchar.h:571:6: error: #if with no expression
     # if
          ^

(From OE-Core rev: 71fae8ac66f0aa3239b3daf5d21cba9bd31d85ad)

Signed-off-by: Leonardo Sandoval <leonardo.sandoval.gonzalez@linux.intel.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>