webkitgtk: Add opengl to REQUIRED_DISTRO_FEATURES
webkitgtk depends on gtk4 which has the below logic, so add the
same logic for webkitgtk.
REQUIRED_DISTRO_FEATURES = "opengl"

Fixes:
  ERROR: Nothing PROVIDES 'gtk4' (but /build/layers/oe-core/meta/recipes-sato/webkit/webkitgtk_2.40.5.bb DEPENDS on or otherwise requires it)
  gtk4 was skipped: missing required distro feature 'opengl' (not in DISTRO_FEATURES)
  ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
  Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'webkitgtk', 'gtk4']

(From OE-Core rev: ac9fd3afa56f91bb43ebff4653b49ccc3af50e4c)

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>
Signed-off-by: Alexandre Belloni <alexandre.belloni@bootlin.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>